[2022-02-05 19:34:30,122] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: beginner_batch_processing.create_emr_cluster manual__2022-02-05T19:31:57.468572+00:00 [queued]>
[2022-02-05 19:34:30,130] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: beginner_batch_processing.create_emr_cluster manual__2022-02-05T19:31:57.468572+00:00 [queued]>
[2022-02-05 19:34:30,130] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-05 19:34:30,130] {taskinstance.py:1239} INFO - Starting attempt 3 of 3
[2022-02-05 19:34:30,131] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-05 19:34:30,140] {taskinstance.py:1259} INFO - Executing <Task(EmrCreateJobFlowOperator): create_emr_cluster> on 2022-02-05 19:31:57.468572+00:00
[2022-02-05 19:34:30,145] {standard_task_runner.py:52} INFO - Started process 748 to run task
[2022-02-05 19:34:30,148] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'beginner_batch_processing', 'create_emr_cluster', 'manual__2022-02-05T19:31:57.468572+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/beginner_batch_processing.py', '--cfg-path', '/tmp/tmpuf34ricl', '--error-file', '/tmp/tmpv53idbk_']
[2022-02-05 19:34:30,148] {standard_task_runner.py:77} INFO - Job 18: Subtask create_emr_cluster
[2022-02-05 19:34:30,191] {logging_mixin.py:109} INFO - Running <TaskInstance: beginner_batch_processing.create_emr_cluster manual__2022-02-05T19:31:57.468572+00:00 [running]> on host 3479a57d1d64
[2022-02-05 19:34:30,241] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=beginner_batch_processing
AIRFLOW_CTX_TASK_ID=create_emr_cluster
AIRFLOW_CTX_EXECUTION_DATE=2022-02-05T19:31:57.468572+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-05T19:31:57.468572+00:00
[2022-02-05 19:34:30,241] {emr_create_job_flow.py:95} INFO - Creating JobFlow using aws-conn-id: aws_default, emr-conn-id: emr_default
[2022-02-05 19:34:30,260] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/emr_create_job_flow.py", line 103, in execute
    response = emr.create_job_flow(job_flow_overrides)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/emr.py", line 83, in create_job_flow
    emr_conn = self.get_connection(self.emr_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 68, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 410, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `emr_default` isn't defined
[2022-02-05 19:34:30,266] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=beginner_batch_processing, task_id=create_emr_cluster, execution_date=20220205T193157, start_date=20220205T193430, end_date=20220205T193430
[2022-02-05 19:34:30,277] {standard_task_runner.py:92} ERROR - Failed to execute job 18 for task create_emr_cluster
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/emr_create_job_flow.py", line 103, in execute
    response = emr.create_job_flow(job_flow_overrides)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/emr.py", line 83, in create_job_flow
    emr_conn = self.get_connection(self.emr_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 68, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 410, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `emr_default` isn't defined
[2022-02-05 19:34:30,320] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-05 19:34:30,353] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
