[2022-02-05 19:36:23,394] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: beginner_batch_processing.create_emr_cluster manual__2022-02-05T19:31:57.468572+00:00 [failed]>
[2022-02-05 19:36:23,407] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: beginner_batch_processing.create_emr_cluster manual__2022-02-05T19:31:57.468572+00:00 [failed]>
[2022-02-05 19:36:23,407] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-05 19:36:23,407] {taskinstance.py:1239} INFO - Starting attempt 4 of 3
[2022-02-05 19:36:23,407] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-05 19:36:23,418] {taskinstance.py:1259} INFO - Executing <Task(EmrCreateJobFlowOperator): create_emr_cluster> on 2022-02-05 19:31:57.468572+00:00
[2022-02-05 19:36:23,423] {standard_task_runner.py:52} INFO - Started process 838 to run task
[2022-02-05 19:36:23,427] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'beginner_batch_processing', 'create_emr_cluster', 'manual__2022-02-05T19:31:57.468572+00:00', '--job-id', '19', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/beginner_batch_processing.py', '--cfg-path', '/tmp/tmp18pl67yk', '--error-file', '/tmp/tmpexvl7uze']
[2022-02-05 19:36:23,428] {standard_task_runner.py:77} INFO - Job 19: Subtask create_emr_cluster
[2022-02-05 19:36:23,535] {logging_mixin.py:109} INFO - Running <TaskInstance: beginner_batch_processing.create_emr_cluster manual__2022-02-05T19:31:57.468572+00:00 [running]> on host 3479a57d1d64
[2022-02-05 19:36:23,619] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=beginner_batch_processing
AIRFLOW_CTX_TASK_ID=create_emr_cluster
AIRFLOW_CTX_EXECUTION_DATE=2022-02-05T19:31:57.468572+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-05T19:31:57.468572+00:00
[2022-02-05 19:36:23,620] {emr_create_job_flow.py:95} INFO - Creating JobFlow using aws-conn-id: aws_default, emr-conn-id: emr_default
[2022-02-05 19:36:23,632] {base_aws.py:401} INFO - Airflow Connection: aws_conn_id=aws_default
[2022-02-05 19:36:23,642] {base_aws.py:177} INFO - Credentials retrieved from login
[2022-02-05 19:36:23,642] {base_aws.py:88} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-02-05 19:36:23,643] {base_aws.py:93} INFO - Creating session with aws_access_key_id=AKIA53YL7CVELHKGVOP4 region_name=us-east-1
[2022-02-05 19:36:23,659] {base_aws.py:168} INFO - role_arn is None
[2022-02-05 19:36:23,660] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/amazon/aws/hooks/base_aws.py:494: DeprecationWarning: client_type is deprecated. Set client_type from class attribute.
  return self.get_client_type(self.client_type, region_name=self.region_name)

[2022-02-05 19:36:23,714] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/emr_create_job_flow.py", line 103, in execute
    response = emr.create_job_flow(job_flow_overrides)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/emr.py", line 88, in create_job_flow
    response = self.get_conn().run_job_flow(**config)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 681, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 729, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/validate.py", line 360, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "region_name", must be one of: Name, LogUri, LogEncryptionKmsKeyId, AdditionalInfo, AmiVersion, ReleaseLabel, Instances, Steps, BootstrapActions, SupportedProducts, NewSupportedProducts, Applications, Configurations, VisibleToAllUsers, JobFlowRole, ServiceRole, Tags, SecurityConfiguration, AutoScalingRole, ScaleDownBehavior, CustomAmiId, EbsRootVolumeSize, RepoUpgradeOnBoot, KerberosAttributes, StepConcurrencyLevel, ManagedScalingPolicy, PlacementGroupConfigs, AutoTerminationPolicy
[2022-02-05 19:36:23,730] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=beginner_batch_processing, task_id=create_emr_cluster, execution_date=20220205T193157, start_date=20220205T193623, end_date=20220205T193623
[2022-02-05 19:36:23,746] {standard_task_runner.py:92} ERROR - Failed to execute job 19 for task create_emr_cluster
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/emr_create_job_flow.py", line 103, in execute
    response = emr.create_job_flow(job_flow_overrides)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/emr.py", line 88, in create_job_flow
    response = self.get_conn().run_job_flow(**config)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 681, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 729, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/validate.py", line 360, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "region_name", must be one of: Name, LogUri, LogEncryptionKmsKeyId, AdditionalInfo, AmiVersion, ReleaseLabel, Instances, Steps, BootstrapActions, SupportedProducts, NewSupportedProducts, Applications, Configurations, VisibleToAllUsers, JobFlowRole, ServiceRole, Tags, SecurityConfiguration, AutoScalingRole, ScaleDownBehavior, CustomAmiId, EbsRootVolumeSize, RepoUpgradeOnBoot, KerberosAttributes, StepConcurrencyLevel, ManagedScalingPolicy, PlacementGroupConfigs, AutoTerminationPolicy
[2022-02-05 19:36:23,761] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-05 19:36:23,801] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
